function(add_files ADD_FILES_OUTPUT ADD_FILES_NAME ADD_FILES_EXTENSION)

  file(GLOB_RECURSE FILES_SOURCE_TMP RELATIVE
    "${CMAKE_CURRENT_SOURCE_DIR}/${ADD_FILES_NAME}"
    "${CMAKE_CURRENT_SOURCE_DIR}/${ADD_FILES_NAME}/*.${ADD_FILES_EXTENSION}")
    
  set(FILES_OUTPUT_TMP "")
  foreach(filename ${FILES_SOURCE_TMP})
    list(APPEND FILES_OUTPUT_TMP ${CMAKE_CURRENT_SOURCE_DIR}/${ADD_FILES_NAME}/${filename})
  endforeach(filename)
 
  set(${ADD_FILES_OUTPUT} ${${ADD_FILES_OUTPUT}} ${FILES_OUTPUT_TMP} PARENT_SCOPE)
  
endfunction()

macro(add_project_source_dir PROJECT_NAME DIRECTORY_NAME SOURCE_FILES)

  set_parent_scope(PROJECT_${PROJECT_NAME}_SOURCE_DIRECTORIES ${PROJECT_${PROJECT_NAME}_SOURCE_DIRECTORIES} ${DIRECTORY_NAME})
  set_parent_scope(PROJECT_${PROJECT_NAME}_SOURCE_DIR_${DIRECTORY_NAME} ${ADD_SOURCE_DIRECTORY_OUTPUT_TMP})

endmacro()

macro(add_source_directory ADD_SOURCE_DIRECTORY_NAME)
  
  set(ADD_SOURCE_DIRECTORY_OUTPUT_TMP "")
  add_files(ADD_SOURCE_DIRECTORY_OUTPUT_TMP ${ADD_SOURCE_DIRECTORY_NAME} "cpp")
  add_files(ADD_SOURCE_DIRECTORY_OUTPUT_TMP ${ADD_SOURCE_DIRECTORY_NAME} "h")
  
  add_project_source_dir(${CURRENT_PROJECT_NAME} ${ADD_SOURCE_DIRECTORY_NAME} ${ADD_SOURCE_DIRECTORY_OUTPUT_TMP})

endmacro()

macro(add_ui_directory ADD_UI_DIRECTORY_NAME)
  
  set(ADD_UI_DIRECTORY_OUTPUT_TMP "")
  add_files(ADD_UI_DIRECTORY_OUTPUT_TMP ${ADD_UI_DIRECTORY_NAME} "ui")
  
  add_project_source_dir(${CURRENT_PROJECT_NAME} ${ADD_UI_DIRECTORY_NAME} ${ADD_UI_DIRECTORY_OUTPUT_TMP})

endmacro()

macro(add_other_directory ADD_OTHER_DIRECTORY_NAME)
  
  set(ADD_OTHER_DIRECTORY_OUTPUT_TMP "")
  add_files(ADD_OTHER_DIRECTORY_OUTPUT_TMP ${ADD_OTHER_DIRECTORY_NAME} "*")
  
  add_project_source_dir(${CURRENT_PROJECT_NAME} ${ADD_OTHER_DIRECTORY_NAME} ${ADD_OTHER_DIRECTORY_OUTPUT_TMP})

endmacro()

macro(add_include_directory ADD_INCLUDE_DIRECTORY_NAME)

  set_parent_scope(
    PROJECT_${CURRENT_PROJECT_NAME}_INCLUDE_DIRECTORIES
    ${PROJECT_${CURRENT_PROJECT_NAME}_INCLUDE_DIRECTORIES}
    ${CMAKE_CURRENT_SOURCE_DIR}/${ADD_INCLUDE_DIRECTORY_NAME})

endmacro()

macro(add_qrc_files)

  set_parent_scope(
    PROJECT_${CURRENT_PROJECT_NAME}_QRC_FILES
    ${PROJECT_${CURRENT_PROJECT_NAME}_QRC_FILES}
    ${ARGV})

endmacro()